### PR TITLE
Completed VTT Hinting sources

### PR DESCRIPTION
**Pull request by mikedug**
Completed VTT Hinting Raleway Roman and Italic Variable fonts

### CODE REVIEW

**Comment by m4rc1e** [comment]
Thanks

**Comment by m4rc1e** [comment]
@pichotta please merge this and I'll send a pr which will compile the hints.

**Comment by m4rc1e** [comment]
If I extract the hinting data using vttLib and then reimport it onto a newly generated font. I get the following traceback:

```
raise VTTLibInvalidComposite(
vttLib.VTTLibInvalidComposite: Component 1 in 'uni04B7' has wrong x offset: expected 386, found 381.
```

I'm wondering if amendments have been made to the sources and they haven't been commited to this repo yet?

cc @pichotta @moyogo

**Comment by mikedug** [comment]
I can make this fix, and update the font, and open a new pull request? or do I just need to update the font? were there any other issues found when importing the hinting?

**Comment by mikedug** [comment]
the font is updated now with the correct offset for uni04B7

**Comment by m4rc1e** [comment]
Thanks!

I've just opened up a pr which includes your hints. I'll quickly diff them and see if we have any issues.

**Pull request merged**
